package com.bloobirds.datamodel.abstraction.logicroles;

import com.bloobirds.datamodel.abstraction.LogicRoles;

public enum ActivityLogicRoles implements LogicRoles {

    ACTIVITY__OPPORTUNITY,
    ACTIVITY__CHANNEL,
    ACTIVITY__COMPANY,
    ACTIVITY__CREATION_DATETIME,
    ACTIVITY__LEAD,
    ACTIVITY__LEAD_EMAIL,
    ACTIVITY__TIME,
    ACTIVITY__TYPE,
    ACTIVITY__UPDATE_DATETIME,
    ACTIVITY__USER,
    NONE


//    ACTIVITY__ACCOUNT_EXECUTIVE
//    ACTIVITY__CADENCE
//    ACTIVITY__CADENCE_TITLE

//    ACTIVITY__CONTACT_RESULT


//    ACTIVITY__EMAIL_HISTORY_CLICK
//    ACTIVITY__EMAIL_HISTORY_OPEN
//    ACTIVITY__EMAIL_HISTORY_REPLY
//    ACTIVITY__EMAIL_LAST_DATE_OPEN
//    ACTIVITY__EMAIL_LEAD
//    ACTIVITY__EMAIL_TIMES_CLICK
//    ACTIVITY__EMAIL_TIMES_OPEN
//    ACTIVITY__EMAIL_TIMES_REPLY
//    ACTIVITY__EMAIL_UID
//    ACTIVITY__EMAIL_USER
//    ACTIVITY__ICON
//    ACTIVITY__ICON_COMPANION
//    ACTIVITY__IMPORT_ID
//    ACTIVITY__INBOUND_FORM_NAME
//    ACTIVITY__INBOUND_LEAD_EMAIL
//    ACTIVITY__INBOUND_PRIORITY
//    ACTIVITY__IS_ATTEMPT
//    ACTIVITY__IS_NOTIFICATION
//    ACTIVITY__IS_PINNED
//    ACTIVITY__IS_TOUCH
//    ACTIVITY__LEAD
//    ACTIVITY__LEAD_EMAIL
//    ACTIVITY__LINKEDIN_MESSAGE_HASH
//    ACTIVITY__LINKEDIN_THREAD
//    ACTIVITY__MEETING_ID
//    ACTIVITY__MEETING_RESULT
//    ACTIVITY__MEETING_TITLE
//    ACTIVITY__MESSAGE_BODY
//    ACTIVITY__MESSAGE_SUBJECT
//    ACTIVITY__NOTE
//    ACTIVITY__NOTIFICATION_OWNER
//    ACTIVITY__NOTIFICATION_OWNER_EMPLOYEE_ROLE
//    ACTIVITY__PITCH
//    ACTIVITY__PITCH_DONE
//    ACTIVITY__REPORTED
//    ACTIVITY__STATUS_TITLE
//    ACTIVITY__TABLE_VIEW_ITEM
//    ACTIVITY__TYPE_CADENCE
//    ACTIVITY__UPDATE_DATETIME
//    ACTIVITY__USER
//    ACTIVITY__USER_EMPLOYEE_ROLE
//    HUBSPOT__ENGAGEMENT_ID
//    MEETING__TYPE
}
