package com.bloobirds.datamodel.abstraction;

public enum ActivityLogicRoles implements LogicRoles {

    ACTIVITY__DATA_SOURCE_AUTOMATED,
    ACTIVITY__USER_EMPLOYEE_ROLE,
    ACTIVITY__NOTIFICATION_OWNER_EMPLOYEE_ROLE,
    ACTIVITY__TABLE_VIEW_ITEM,
    ACTIVITY__REPORTED,
    ACTIVITY__ICON_COMPANION,
    ACTIVITY__OPPORTUNITY,
    ACTIVITY__NOTIFICATION_OWNER,
    ACTIVITY__ICON,
    ACTIVITY__IS_NOTIFICATION,
    ACTIVITY__CHANNEL,
    ACTIVITY__COMPANY,
    ACTIVITY__CREATION_DATETIME,
    ACTIVITY__DATA_SOURCE,
    ACTIVITY__IMPORT_ID,
    ACTIVITY__IS_ATTEMPT,
    ACTIVITY__IS_PINNED,
    ACTIVITY__IS_TOUCH,
    ACTIVITY__LEAD,
    ACTIVITY__LEAD_EMAIL,
    ACTIVITY__TIME,
    ACTIVITY__TYPE,
    ACTIVITY__UPDATE_DATETIME,
    ACTIVITY__USER,
    HUBSPOT__ENGAGEMENT_ID,
    ACTIVITY_NONE
}
